name: suse-leap Runtime Scan

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qemu-system-x86 \
            qemu-utils \
            cloud-image-utils \
            curl \
            libguestfs-tools \
            guestmount \
            netcat-openbsd \
            ca-certificates  

      - name: Download openSUSE qcow2 image
        run: |
          curl -L -o suse-leap.qcow2 \
            https://download.opensuse.org/distribution/leap/16.0/appliances/Leap-16.0-Minimal-VM.x86_64-kvm-and-xen.qcow2

      - name: Mount qcow2 image
        run: |
          sudo mkdir -p /mnt/suse-root
          sudo guestmount -a suse-leap.qcow2 -i --ro /mnt/suse-root

      - name: Run Trivy scan (offline rootfs)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

          sudo ./bin/trivy rootfs /mnt/suse-root \
            --scanners vuln,misconfig \
            -f sarif \
            -o report.sarif

      - name: Unmount qcow2
        if: always()
        run: |
          sudo guestunmount /mnt/suse-root || true

      - name: Upload Trivy SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: report.sarif
